name: bachelors-thesis
dependencies:
  - python=3.12.*
  - pip
  - conda-forge::pytest
  - numpy
  - pytorch::faiss-cpu
  - networkx
  - conda-forge::pandas
  - conda-forge::geopandas
  - scipy
  - conda-forge::scikit-learn
  - matplotlib
#  - Levenshtein