name: bachelors-thesis
dependencies:
  - conda-forge::python=3.12.9
  - conda-forge::pip=25.0.1
  - conda-forge::pytest=8.3.5
  - conda-forge::numpy
  - pytorch::faiss-gpu=1.11.0
  - conda-forge::networkx=3.4.2
  - conda-forge::scipy=1.15.2
  - conda-forge::scikit-learn=1.6.1
  - conda-forge::matplotlib=3.10.1
  - conda-forge::osmnx=2.0.2
  - conda-forge::pandas=2.2.3
  - conda-forge::geopandas=1.0.1
  - conda-forge::shapely=2.1.0
  - conda-forge::pyproj=3.7.1
  - conda-forge::levenshtein=0.27.1
  - conda-forge::jupyterlab=4.4.1
  - conda-forge::libsqlite=3.49.1

# libsqlite is needed, because the Jupyter server keeps crashing
# See https://stackoverflow.com/questions/74837553/how-to-fix-a-mac-base-conda-environment-when-sqlite3-is-broken
# conda install -c conda-forge libsqlite=3.49.1 --force-reinstall -y
#
# faiss-gpu needs to be similarly installed
# conda install -c pytorch -c nvidia faiss-gpu=1.11.0 --force-reinstall -y
#
# mappymatch needs to be installed through pip, since it's not available as a conda package
# pip install mappymatch
