name: bachelors-thesis
dependencies:
  - conda-forge::python=3.*.*
  - conda-forge::pip
  - conda-forge::pytest
  - conda-forge::numpy
  - pytorch::faiss-cpu
  - pytorch::faiss-gpu
  - conda-forge::networkx
  - conda-forge::scipy
  - conda-forge::scikit-learn
  - conda-forge::matplotlib
#  - Levenshtein