# TODO: Try adding different (smaller) K for merging
K = 129
DIMENSION = 256
NUMBER_OF_THREADS = 4
SIMILARITY_THRESHOLD = 0.85
# TODO: Try tuning merging-threshold
MERGING_THRESHOLD = 0.6
WEIGHT_VEHICLE_SIMILARITY = 0.2
WEIGHT_LICENSE_PLATE_SIMILARITY = 0.8

NUMBER_OF_ANNOTATED_VEHICLES = 173
NUMBER_OF_CAMERAS = 157
NUMBER_OF_TRAJECTORIES = 168
