# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: networking.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'networking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10networking.proto\x12\x10\x62\x61\x63helors_thesis\"\xca\x01\n\x07\x43luster\x12\x12\n\ncluster_id\x18\x01 \x01(\t\x12 \n\x18\x63\x65ntroid_vehicle_feature\x18\x02 \x03(\x02\x12&\n\x1e\x63\x65ntroid_license_plate_feature\x18\x03 \x03(\x02\x12#\n\x1b\x63\x65ntroid_license_plate_text\x18\x04 \x01(\t\x12\x11\n\tnode_path\x18\x05 \x03(\r\x12)\n\x07records\x18\x06 \x03(\x0b\x32\x18.bachelors_thesis.Record\"U\n\x06Record\x12\x11\n\trecord_id\x18\x01 \x01(\t\x12\x11\n\tcamera_id\x18\x02 \x01(\r\x12\x12\n\nvehicle_id\x18\x03 \x01(\x11\x12\x11\n\ttimestamp\x18\x04 \x01(\x11\"S\n\x08\x45nvelope\x12\x0e\n\x04\x64one\x18\x01 \x01(\x08H\x00\x12,\n\x07\x63luster\x18\x02 \x01(\x0b\x32\x19.bachelors_thesis.ClusterH\x00\x42\t\n\x07\x63ontentb\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'networking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals['_CLUSTER']._serialized_start = 39
    _globals['_CLUSTER']._serialized_end = 241
    _globals['_RECORD']._serialized_start = 243
    _globals['_RECORD']._serialized_end = 328
    _globals['_ENVELOPE']._serialized_start = 330
    _globals['_ENVELOPE']._serialized_end = 413
# @@protoc_insertion_point(module_scope)
